dist: trusty
sudo: required
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
before_install:
  - sudo apt-get -qq update
install:
  - type -p cargo-install-update || cargo install cargo-update
  - cargo install-update -i cargo-update
  - cargo install-update -i rustfmt
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo install-update -i clippy;
    fi
script:
  - cargo fmt -- --write-mode=diff
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo clippy;
    fi
  - cargo build
